---
sunbird_auth_version: 1.0v
keycloak_pkg_src: https://downloads.jboss.org/keycloak/3.2.0.Final/keycloak-3.2.0.Final.tar.gz
postgresql_driver_src: https://jdbc.postgresql.org/download/postgresql-9.4.1212.jar
